[project]
name = "soundtoact"
version = "0.1.0"
description = "Voice-triggered automation app"
requires-python = ">=3.13"
dependencies = [
    "SpeechRecognition>=3.10.0",
    "pyaudio>=0.2.14",
    "openai-whisper>=20230314",
    "torch>=2.0.0",
]
